meta:
  en:
    name: Skip IE first run custom settings
    from: DISM++（by 原罪、恋人の共鸣）
  zh:
    name: 跳过IE首次运行自定义设置
applyDefaultUser: true
tweaks:
  registry:
    - key: 'HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main'
      valueName: "RunOnceHasShown"
      type: "REG_DWORD"
      value: "1"
    - key: 'HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main'
      valueName: "RunOnceComplete"
      type: "REG_DWORD"
      value: "1"
    - key: 'HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main'
      valueName: "DisableFirstRunCustomize"
      type: "REG_DWORD"
      value: "1"
